//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_ABSTRACT_ITEM
    {
        public MW_ABSTRACT_ITEM()
        {
            this.MW_SEARCHABLE_ITEM = new HashSet<MW_SEARCHABLE_ITEM>();
        }
    
        public int category_id { get; set; }
        public int abstract_item_id { get; set; }
        public string material { get; set; }
        public string gender { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<float> upper_price { get; set; }
        public Nullable<float> lower_price { get; set; }
    
        public virtual MW_CATEGORY MW_CATEGORY { get; set; }
        public virtual MW_BRAND MW_BRAND { get; set; }
        public virtual ICollection<MW_SEARCHABLE_ITEM> MW_SEARCHABLE_ITEM { get; set; }
    }
}
