//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_BRAND
    {
        public MW_BRAND()
        {
            this.MW_ABSTRACT_ITEM = new HashSet<MW_ABSTRACT_ITEM>();
        }
    
        public int brand_id { get; set; }
        public string brand_name { get; set; }
    
        public virtual ICollection<MW_ABSTRACT_ITEM> MW_ABSTRACT_ITEM { get; set; }
        public virtual MW_BRAND_CN MW_BRAND_CN { get; set; }
    }
}
