//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_COLOUR
    {
        public MW_COLOUR()
        {
            this.MW_COLOUR_RELATIONSHIP = new HashSet<MW_COLOUR_RELATIONSHIP>();
            this.MW_COLOUR_RELATIONSHIP1 = new HashSet<MW_COLOUR_RELATIONSHIP>();
            this.MW_SEARCHABLE_ITEM = new HashSet<MW_SEARCHABLE_ITEM>();
            this.MW_UPLOADED_ITEM = new HashSet<MW_UPLOADED_ITEM>();
        }
    
        public int colour_id { get; set; }
        public string colour_name { get; set; }
    
        public virtual MW_COLOUR_CN MW_COLOUR_CN { get; set; }
        public virtual ICollection<MW_COLOUR_RELATIONSHIP> MW_COLOUR_RELATIONSHIP { get; set; }
        public virtual ICollection<MW_COLOUR_RELATIONSHIP> MW_COLOUR_RELATIONSHIP1 { get; set; }
        public virtual ICollection<MW_SEARCHABLE_ITEM> MW_SEARCHABLE_ITEM { get; set; }
        public virtual ICollection<MW_UPLOADED_ITEM> MW_UPLOADED_ITEM { get; set; }
    }
}
