//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_COLOUR_CN
    {
        public int colour_id { get; set; }
        public string colour_name { get; set; }
    
        public virtual MW_COLOUR MW_COLOUR { get; set; }
    }
}
