//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_CATEGORY
    {
        public MW_CATEGORY()
        {
            this.MW_ABSTRACT_ITEM = new HashSet<MW_ABSTRACT_ITEM>();
            this.MW_CATEGORY_RELATIONSHIP = new HashSet<MW_CATEGORY_RELATIONSHIP>();
            this.MW_CATEGORY_RELATIONSHIP1 = new HashSet<MW_CATEGORY_RELATIONSHIP>();
            this.MW_UPLOADED_ITEM = new HashSet<MW_UPLOADED_ITEM>();
        }
    
        public int category_id { get; set; }
        public string category_name { get; set; }
    
        public virtual ICollection<MW_ABSTRACT_ITEM> MW_ABSTRACT_ITEM { get; set; }
        public virtual MW_CATEGORY_CN MW_CATEGORY_CN { get; set; }
        public virtual ICollection<MW_CATEGORY_RELATIONSHIP> MW_CATEGORY_RELATIONSHIP { get; set; }
        public virtual ICollection<MW_CATEGORY_RELATIONSHIP> MW_CATEGORY_RELATIONSHIP1 { get; set; }
        public virtual ICollection<MW_UPLOADED_ITEM> MW_UPLOADED_ITEM { get; set; }
    }
}
