//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_OUTFIT_ITEM
    {
        public int outfit_id { get; set; }
        public int searchable_item_id { get; set; }
        public int pic_x { get; set; }
        public int pic_y { get; set; }
        public Nullable<float> angle { get; set; }
        public Nullable<float> crop_x { get; set; }
        public Nullable<float> crop_y { get; set; }
        public Nullable<float> crop_width { get; set; }
        public Nullable<float> crop_height { get; set; }
        public Nullable<float> sizing_factor { get; set; }
        public int z_index { get; set; }
    
        public virtual MW_OUTFIT MW_OUTFIT { get; set; }
        public virtual MW_SEARCHABLE_ITEM MW_SEARCHABLE_ITEM { get; set; }
    }
}
