//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_OUTFIT
    {
        public MW_OUTFIT()
        {
            this.MW_OUTFIT_ITEM = new HashSet<MW_OUTFIT_ITEM>();
            this.MW_USER_RATE_OUTFIT = new HashSet<MW_USER_RATE_OUTFIT>();
            this.MW_USER_TAG_OUTFIT = new HashSet<MW_USER_TAG_OUTFIT>();
        }
    
        public int outfit_id { get; set; }
        public string name { get; set; }
        public int picture_id { get; set; }
    
        public virtual ICollection<MW_OUTFIT_ITEM> MW_OUTFIT_ITEM { get; set; }
        public virtual ICollection<MW_USER_RATE_OUTFIT> MW_USER_RATE_OUTFIT { get; set; }
        public virtual ICollection<MW_USER_TAG_OUTFIT> MW_USER_TAG_OUTFIT { get; set; }
    }
}
