//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_PICTURE
    {
        public MW_PICTURE()
        {
            this.MW_ITEM_PICTURE = new HashSet<MW_ITEM_PICTURE>();
            this.MW_SEARCHABLE_ITEM = new HashSet<MW_SEARCHABLE_ITEM>();
            this.MW_TAG = new HashSet<MW_TAG>();
            this.MW_UPLOADED_ITEM = new HashSet<MW_UPLOADED_ITEM>();
            this.MW_USER = new HashSet<MW_USER>();
        }
    
        public int picture_id { get; set; }
        public string url { get; set; }
        public int width { get; set; }
        public int height { get; set; }
    
        public virtual ICollection<MW_ITEM_PICTURE> MW_ITEM_PICTURE { get; set; }
        public virtual ICollection<MW_SEARCHABLE_ITEM> MW_SEARCHABLE_ITEM { get; set; }
        public virtual ICollection<MW_TAG> MW_TAG { get; set; }
        public virtual ICollection<MW_UPLOADED_ITEM> MW_UPLOADED_ITEM { get; set; }
        public virtual ICollection<MW_USER> MW_USER { get; set; }
    }
}
