//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_SIZE
    {
        public MW_SIZE()
        {
            this.MW_UNIQ_ITEM = new HashSet<MW_UNIQ_ITEM>();
        }
    
        public int size_id { get; set; }
        public string size_val { get; set; }
        public string size_type { get; set; }
    
        public virtual ICollection<MW_UNIQ_ITEM> MW_UNIQ_ITEM { get; set; }
    }
}
