//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_TAG
    {
        public MW_TAG()
        {
            this.MW_TAG_REL = new HashSet<MW_TAG_REL>();
            this.MW_TAG_REL1 = new HashSet<MW_TAG_REL>();
            this.MW_USER_TAG = new HashSet<MW_USER_TAG>();
            this.MW_SEARCHABLE_ITEM = new HashSet<MW_SEARCHABLE_ITEM>();
        }
    
        public int tag_id { get; set; }
        public string tag_name { get; set; }
        public string tag_type { get; set; }
        public Nullable<int> default_picture { get; set; }
    
        public virtual MW_PICTURE MW_PICTURE { get; set; }
        public virtual ICollection<MW_TAG_REL> MW_TAG_REL { get; set; }
        public virtual ICollection<MW_TAG_REL> MW_TAG_REL1 { get; set; }
        public virtual ICollection<MW_USER_TAG> MW_USER_TAG { get; set; }
        public virtual ICollection<MW_SEARCHABLE_ITEM> MW_SEARCHABLE_ITEM { get; set; }
    }
}
