//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_TAG_REL
    {
        public int source_tag_id { get; set; }
        public int target_tag_id { get; set; }
        public Nullable<float> probability { get; set; }
    
        public virtual MW_TAG MW_TAG { get; set; }
        public virtual MW_TAG MW_TAG1 { get; set; }
    }
}
