//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_USER
    {
        public MW_USER()
        {
            this.MW_REVIEW = new HashSet<MW_REVIEW>();
            this.MW_USER_RATE_OUTFIT = new HashSet<MW_USER_RATE_OUTFIT>();
            this.MW_USER_SSN = new HashSet<MW_USER_SSN>();
            this.MW_USER_TAG = new HashSet<MW_USER_TAG>();
            this.MW_SEARCHABLE_ITEM = new HashSet<MW_SEARCHABLE_ITEM>();
        }
    
        public string user_id { get; set; }
        public bool enable_SSN_login { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string gender { get; set; }
        public string name { get; set; }
        public Nullable<int> credit { get; set; }
        public Nullable<int> experience { get; set; }
        public string occupation { get; set; }
        public string nationality { get; set; }
        public string location { get; set; }
        public Nullable<int> profile_picture { get; set; }
    
        public virtual MW_PICTURE MW_PICTURE { get; set; }
        public virtual ICollection<MW_REVIEW> MW_REVIEW { get; set; }
        public virtual ICollection<MW_USER_RATE_OUTFIT> MW_USER_RATE_OUTFIT { get; set; }
        public virtual ICollection<MW_USER_SSN> MW_USER_SSN { get; set; }
        public virtual ICollection<MW_USER_TAG> MW_USER_TAG { get; set; }
        public virtual ICollection<MW_SEARCHABLE_ITEM> MW_SEARCHABLE_ITEM { get; set; }
    }
}
