//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_UPLOADED_ITEM
    {
        public MW_UPLOADED_ITEM()
        {
            this.MW_USER_TAG_UPLOADED = new HashSet<MW_USER_TAG_UPLOADED>();
        }
    
        public int upload_item_id { get; set; }
        public string name { get; set; }
        public int colour_id { get; set; }
        public int category_id { get; set; }
        public int picture_id { get; set; }
    
        public virtual MW_CATEGORY MW_CATEGORY { get; set; }
        public virtual MW_COLOUR MW_COLOUR { get; set; }
        public virtual MW_PICTURE MW_PICTURE { get; set; }
        public virtual ICollection<MW_USER_TAG_UPLOADED> MW_USER_TAG_UPLOADED { get; set; }
    }
}
