//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_USER_TAG
    {
        public MW_USER_TAG()
        {
            this.MW_USER_TAG_OUTFIT = new HashSet<MW_USER_TAG_OUTFIT>();
            this.MW_USER_TAG_ITEM = new HashSet<MW_USER_TAG_ITEM>();
            this.MW_USER_TAG_UPLOADED = new HashSet<MW_USER_TAG_UPLOADED>();
        }
    
        public string user_id { get; set; }
        public int tag_id { get; set; }
        public System.DateTime create_time { get; set; }
        public int tag_picture { get; set; }
    
        public virtual MW_TAG MW_TAG { get; set; }
        public virtual MW_USER MW_USER { get; set; }
        public virtual ICollection<MW_USER_TAG_OUTFIT> MW_USER_TAG_OUTFIT { get; set; }
        public virtual ICollection<MW_USER_TAG_ITEM> MW_USER_TAG_ITEM { get; set; }
        public virtual ICollection<MW_USER_TAG_UPLOADED> MW_USER_TAG_UPLOADED { get; set; }
    }
}
