//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWDataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MWDBEntities : DbContext
    {
        public MWDBEntities()
            : base("name=MWDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MW_ABSTRACT_ITEM> MW_ABSTRACT_ITEM { get; set; }
        public DbSet<MW_ADDRESS> MW_ADDRESS { get; set; }
        public DbSet<MW_APPAREL_SOURCE> MW_APPAREL_SOURCE { get; set; }
        public DbSet<MW_BRAND> MW_BRAND { get; set; }
        public DbSet<MW_BRAND_CN> MW_BRAND_CN { get; set; }
        public DbSet<MW_CATEGORY> MW_CATEGORY { get; set; }
        public DbSet<MW_CATEGORY_CN> MW_CATEGORY_CN { get; set; }
        public DbSet<MW_CATEGORY_RELATIONSHIP> MW_CATEGORY_RELATIONSHIP { get; set; }
        public DbSet<MW_COLOUR> MW_COLOUR { get; set; }
        public DbSet<MW_COLOUR_CN> MW_COLOUR_CN { get; set; }
        public DbSet<MW_COLOUR_RELATIONSHIP> MW_COLOUR_RELATIONSHIP { get; set; }
        public DbSet<MW_ITEM_MATCHINGNESS> MW_ITEM_MATCHINGNESS { get; set; }
        public DbSet<MW_ITEM_PICTURE> MW_ITEM_PICTURE { get; set; }
        public DbSet<MW_ITEM_SIMILARITY> MW_ITEM_SIMILARITY { get; set; }
        public DbSet<MW_OUTFIT> MW_OUTFIT { get; set; }
        public DbSet<MW_OUTFIT_ITEM> MW_OUTFIT_ITEM { get; set; }
        public DbSet<MW_PICTURE> MW_PICTURE { get; set; }
        public DbSet<MW_REVIEW> MW_REVIEW { get; set; }
        public DbSet<MW_SEARCHABLE_ITEM> MW_SEARCHABLE_ITEM { get; set; }
        public DbSet<MW_SIZE> MW_SIZE { get; set; }
        public DbSet<MW_TAG> MW_TAG { get; set; }
        public DbSet<MW_TAG_REL> MW_TAG_REL { get; set; }
        public DbSet<MW_UNIQ_ITEM> MW_UNIQ_ITEM { get; set; }
        public DbSet<MW_UPLOADED_ITEM> MW_UPLOADED_ITEM { get; set; }
        public DbSet<MW_USER> MW_USER { get; set; }
        public DbSet<MW_USER_RATE_OUTFIT> MW_USER_RATE_OUTFIT { get; set; }
        public DbSet<MW_USER_SSN> MW_USER_SSN { get; set; }
        public DbSet<MW_USER_TAG> MW_USER_TAG { get; set; }
        public DbSet<MW_USER_TAG_ITEM> MW_USER_TAG_ITEM { get; set; }
        public DbSet<MW_USER_TAG_OUTFIT> MW_USER_TAG_OUTFIT { get; set; }
        public DbSet<MW_USER_TAG_UPLOADED> MW_USER_TAG_UPLOADED { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
